/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sema.project;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author semao
 */
public class personalize extends javax.swing.JFrame {

    /**
     * Creates new form personalize
     */
    String sender1 ;
    public personalize(String name) {
        initComponents();
         sender1 =name;
          // Favori listesini başlatıyoruz
        list_favories.setModel(new DefaultListModel<>());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        cb_color = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        rb_male = new javax.swing.JRadioButton();
        rb_famale = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        gbSpinner = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        goBack = goBack = new RoundButton("");
        jScrollPane1 = new javax.swing.JScrollPane();
        list_favories = new javax.swing.JList<>();
        txt_favories = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        add_button = new javax.swing.JButton();
        delete_button = new javax.swing.JButton();
        update_button = new javax.swing.JButton();
        list_button = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_contactUs = new javax.swing.JMenu();
        menu_writeUs = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(233, 249, 249));

        cb_color.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default", "Dark blue", "Ligth blue" }));
        cb_color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_colorActionPerformed(evt);
            }
        });

        jLabel2.setText("change screen color:");

        buttonGroup1.add(rb_male);
        rb_male.setText("male");

        buttonGroup1.add(rb_famale);
        rb_famale.setText("female");
        rb_famale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_famaleActionPerformed(evt);
            }
        });

        jLabel3.setText("Choose your gender:");

        gbSpinner.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 3.0d, 0.5d));

        jLabel5.setText("Maximum GB that can be sent:");

        goBack.setText("go back");
        goBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(list_favories);

        txt_favories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_favoriesActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel6.setText("favorite emails account:");

        add_button.setText("ADD");
        add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_buttonActionPerformed(evt);
            }
        });

        delete_button.setText("DELETE");
        delete_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_buttonActionPerformed(evt);
            }
        });

        update_button.setText("UPDATE");
        update_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_buttonActionPerformed(evt);
            }
        });

        list_button.setText("List favorites");
        list_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(gbSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(133, 133, 133))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(263, Short.MAX_VALUE)
                        .addComponent(goBack)
                        .addGap(230, 230, 230)))
                .addGap(23, 23, 23))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rb_famale, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(rb_male, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_favories, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53))
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cb_color, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(update_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(list_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(delete_button, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(54, 54, 54))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(goBack))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(rb_male)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb_famale)
                                .addGap(92, 92, 92)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gbSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_favories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(add_button)
                                .addGap(18, 18, 18)
                                .addComponent(delete_button)
                                .addGap(18, 18, 18)
                                .addComponent(update_button)
                                .addGap(18, 18, 18)
                                .addComponent(list_button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)))
                        .addComponent(jLabel4)
                        .addGap(0, 81, Short.MAX_VALUE)))
                .addContainerGap())
        );

        menu_contactUs.setText("contact us");

        menu_writeUs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menu_writeUs.setText("write us");
        menu_writeUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_writeUsActionPerformed(evt);
            }
        });
        menu_contactUs.add(menu_writeUs);

        jMenuBar1.add(menu_contactUs);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_colorActionPerformed
      // Seçilen temayı al
      
    int selectedTheme = cb_color.getSelectedIndex();

    // Temaya göre arka plan rengini belirle
    Color selectedColor;
    switch (selectedTheme) {
        case 0:
            selectedColor = new Color(0, 51, 102); // Koyu mavi
            break;
        case 1:
            selectedColor = new Color(173, 216, 230); // Açık mavi
            break;
        default:
            selectedColor = new Color(100, 249, 249); // Varsayılan renk
            break;
    }
        // Arka plan rengini değiştir
    jPanel1.setBackground(selectedColor);

    // Değişiklikleri güncelle
    jPanel1.revalidate();
    }//GEN-LAST:event_cb_colorActionPerformed

    private void rb_famaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_famaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_famaleActionPerformed

    private void goBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackActionPerformed
        // TODO add your handling code here:
               Dashboard db = new Dashboard();
        db.setVisible(true);
        db.pack();
        db.setLocationRelativeTo(this);
        this.dispose();
    }//GEN-LAST:event_goBackActionPerformed

    private void txt_favoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_favoriesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_favoriesActionPerformed

    private void add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_buttonActionPerformed
        // TODO add your handling code here:
String favoriteEmail = txt_favories.getText().trim();
    if (!favoriteEmail.isEmpty()) {
        // Veritabanına eklemeden önce kontrol et
        try (Connection con = DBConnector.getConnection()) {
            String checkQuery = "SELECT COUNT(*) FROM favorite WHERE favories = ? AND sender = ?";
            PreparedStatement checkPs = con.prepareStatement(checkQuery);
            checkPs.setString(1, favoriteEmail);
            checkPs.setString(2, sender1); // Giriş yapan kullanıcının adı
            ResultSet rs = checkPs.executeQuery();
            
            if (rs.next() && rs.getInt(1) > 0) {
                JOptionPane.showMessageDialog(this, "This email is already added to your favorites!");
            } else {
                // Eklenmemişse ekle
                String insertQuery = "INSERT INTO favorite (favories, sender) VALUES (?, ?)";
                PreparedStatement insertPs = con.prepareStatement(insertQuery);
                insertPs.setString(1, favoriteEmail);
                insertPs.setString(2, sender1);
                insertPs.executeUpdate();

                // JList'e ekle
                DefaultListModel<String> model = (DefaultListModel<String>) list_favories.getModel();
                model.addElement(favoriteEmail);

                JOptionPane.showMessageDialog(this, "Favorite email added successfully!");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error adding favorite email!");
        }
    } else {
        JOptionPane.showMessageDialog(this, "Email cannot be empty!");
    }
    }//GEN-LAST:event_add_buttonActionPerformed

    private void delete_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_buttonActionPerformed
        // TODO add your handling code here:
           String selectedEmail = list_favories.getSelectedValue();
    if (selectedEmail != null) {
        // Veritabanından sil
        try (Connection con = DBConnector.getConnection()) {
            String query = "DELETE FROM favorite WHERE favories = ? AND sender = ?";
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, selectedEmail);
            ps.setString(2, sender1); // Giriş yapan kullanıcının adı
            ps.executeUpdate();

            // JList'ten sil
            DefaultListModel<String> model = (DefaultListModel<String>) list_favories.getModel();
            model.removeElement(selectedEmail);

            JOptionPane.showMessageDialog(this, "Favorite email deleted successfully!");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error deleting favorite email!");
        }
    } else {
        JOptionPane.showMessageDialog(this, "Please select an email to delete!");
    }
    }//GEN-LAST:event_delete_buttonActionPerformed

    private void update_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_buttonActionPerformed
        // TODO add your handling code here:
            String selectedEmail = list_favories.getSelectedValue();
    String newEmail = txt_favories.getText().trim();

    if (selectedEmail != null && !newEmail.isEmpty()) {
        // Veritabanında güncelle
        try (Connection con = DBConnector.getConnection()) {
            String query = "UPDATE favorite SET favories = ? WHERE favories = ? AND sender = ?";
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, newEmail);
            ps.setString(2, selectedEmail);
            ps.setString(3, sender1); // Giriş yapan kullanıcının adı
            ps.executeUpdate();

            // JList'te güncelle
            DefaultListModel<String> model = (DefaultListModel<String>) list_favories.getModel();
            int selectedIndex = list_favories.getSelectedIndex();
            model.setElementAt(newEmail, selectedIndex);

            JOptionPane.showMessageDialog(this, "Favorite email updated successfully!");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error updating favorite email!");
        }
    } else {
        JOptionPane.showMessageDialog(this, "Please select an email and enter the new email!");
    }
    }//GEN-LAST:event_update_buttonActionPerformed

    private void list_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_buttonActionPerformed
        // TODO add your handling code here:
           // Favorileri listele
    try (Connection con = DBConnector.getConnection()) {
        String query = "SELECT favories FROM favorite WHERE sender = ?";
        PreparedStatement ps = con.prepareStatement(query);
        ps.setString(1, sender1); // Giriş yapan kullanıcının adı
        ResultSet rs = ps.executeQuery();

        // JList'in modelini temizle ve yeni verileri ekle
        DefaultListModel<String> model = (DefaultListModel<String>) list_favories.getModel();
        model.clear();
        while (rs.next()) {
            model.addElement(rs.getString("favories"));
        }

        JOptionPane.showMessageDialog(this, "Favorites listed successfully!");
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error listing favorite emails!");
    }
    }//GEN-LAST:event_list_buttonActionPerformed

    private void menu_writeUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_writeUsActionPerformed
        // TODO add your handling code here:
        feedback fb = new feedback(sender1);
        fb.setVisible(true);
        fb.pack();
        fb.setLocationRelativeTo(this);
       // fb.dispose();
    }//GEN-LAST:event_menu_writeUsActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_button;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cb_color;
    private javax.swing.JButton delete_button;
    private javax.swing.JSpinner gbSpinner;
    private javax.swing.JButton goBack;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton list_button;
    private javax.swing.JList<String> list_favories;
    private javax.swing.JMenu menu_contactUs;
    private javax.swing.JMenuItem menu_writeUs;
    private javax.swing.JRadioButton rb_famale;
    private javax.swing.JRadioButton rb_male;
    private javax.swing.JTextField txt_favories;
    private javax.swing.JButton update_button;
    // End of variables declaration//GEN-END:variables
}
